keyboard:
  matrix_positions:
    - [[1,1], [2,1], [3,1], [4,1], [5,1], [6,1],                  [13,1], [14,1], [15,1], [16,1], [17,1], [18,1]]
    - [[1,2], [2,2], [3,2], [4,2], [5,2], [6,2],                  [13,2], [14,2], [15,2], [16,2], [17,2], [18,2]]
    - [[1,3], [2,3], [3,3], [4,3], [5,3], [6,3],                  [13,3], [14,3], [15,3], [16,3], [17,3], [18,3]]
    - [                            [5,4], [6,4], [7,4],   [12,4], [13,4], [14,4]                                ]

  positions:
    - [[0.5, 65.5], [50.5, 65.5], [100.5, 55.5], [150.5, 50.5], [200.5, 55.5], [250.5, 60.6],                              [450.5, 60.5], [500.5, 55.5], [550.5, 50.5], [600.5, 55.5], [650.5, 65.5], [700.6, 65.5]]
    - [[0.5,115.5], [50.5,115.5], [100.5,105.5], [150.5,100.5], [200.5,105.5], [250.5,110.5],                              [450.5,110.5], [500.5,105.5], [550.5,100.5], [600.5,105.5], [650.5,115.5], [700.6,115.5]]
    - [[0.5,165.5], [50.5,165.5], [100.5,155.5], [150.5,150.5], [200.5,155.5], [250.5,160.5],                              [450.5,160.5], [500.5,155.5], [550.5,150.5], [600.5,155.5], [650.5,165.5], [700.6,165.5]]
    - [                                                   [175.5,210.5],    [230.5,210.5],  [290.5,210.5],   [410.5,210.5],   [470.5,210.5],    [525.5,210.5]                                                      ]

  hands:
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [Left, Left, Left, Left, Left, Left,                Right, Right, Right, Right, Right, Right]
    - [                        Left, Left, Left,   Right, Right, Right                            ]

  fingers:
    - [Pinky, Pinky, Ring,  Middle, Index, Index,                 Index, Index, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Index, Index,                 Index, Index, Middle, Ring,  Pinky, Pinky]
    - [Pinky, Pinky, Ring,  Middle, Index, Index,                 Index, Index, Middle, Ring,  Pinky, Pinky]
    - [                             Thumb,   Thumb,   Thumb,   Thumb, Thumb,   Thumb,                              ]

  key_costs:
    - [25, 20,  9,  5, 11, 17,           17, 11,  5,  9, 20, 25]
    - [ 9,  5,  3,  2,  2,  8,            8,  2,  2,  3,  5,  9]
    - [25, 10, 11, 11,  7, 11,           11,  7, 11, 11, 10, 25]
    - [                 7,  3,  5,    5,  3,  7                ]

  unbalancing_positions:
    - [[-1,  1], [0, 0.5], [0,   0], [0,  0], [0, 0.5], [1,    1],                  [-1,    1], [0, 0.5], [0, 0], [0,   0], [0, 0.5], [1,  1]]
    - [[-1,  0], [0,   0], [0,   0], [0,  0], [0,   0], [1,    0],                  [-1,    0], [0,   0], [0, 0], [0,   0], [0,   0], [1,  0]]
    - [[-1, -1], [0,   0], [0,   0], [0,  0], [0,   0], [1,   -1],                  [-1,   -1], [0,   0], [0, 0], [0,   0], [0,   0], [1, -1]]
    - [                                       [0,   0], [0,    0],  [0, 0], [0, 0], [0,   0],   [0,   0],                                    ]

  symmetries:
    - [  9, 10, 11, 12, 13, 14,           14, 13, 12, 11, 10,  9]
    - [ 15, 16, 17, 18, 19, 20,           20, 19, 18, 17, 16, 15]
    - [ 21, 22, 23, 24, 25, 26,           26, 25, 24, 23, 22, 21]
    - [                 27, 28, 29,   29, 28, 27                ]

  finger_resting_positions:
    Left:
      Pinky: [50.5, 115.5]
      Ring: [100.5, 115.5]
      Middle: [150.5, 115.5]
      Index: [200.5, 115.5]
      Thumb: [230.5, 210.5]
    Right:
      Pinky: [650.5, 115.5]
      Ring: [600.5, 115.5]
      Middle: [550.5, 115.5]
      Index: [500.5, 115.5]
      Thumb: [470.5, 210.5]


  plot_template: |2
                â”Œâ”€â”€â”€â”                         â”Œâ”€â”€â”€â”
            â”Œâ”€â”€â”€â”¤ {{3}} â”œâ”€â”€â”€â”¬â”€â”€â”€â”         â”Œâ”€â”€â”€â”¬â”€â”€â”€â”¤ {{8}} â”œâ”€â”€â”€â”
    â”Œâ”€â”€â”€â”¬â”€â”€â”€â”¤ {{2}} â”œâ”€â”€â”€â”¤ {{4}} â”‚ {{5}} â”‚         â”‚ {{6}} â”‚ {{7}} â”œâ”€â”€â”€â”¤ {{9}} â”œâ”€â”€â”€â”¬â”€â”€â”€â”
    â”‚ {{0}} â”‚ {{1}} â”œâ”€â”€â”€â”¤ {{15}} â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤         â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤ {{20}} â”œâ”€â”€â”€â”¤ {{10}} â”‚ {{11}} â”‚
    â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤ {{14}} â”œâ”€â”€â”€â”¤ {{16}} â”‚ {{17}} â”‚         â”‚ {{18}} â”‚ {{19}} â”œâ”€â”€â”€â”¤ {{21}} â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤
    â”‚ {{12}} â”‚ {{13}} â”œâ”€â”€â”€â”¤ {{27}} â”œâ”€â”â”€â”¼â”€â”€â”€â”¤         â”œâ”€â”€â”€â”¼â”€â”â”€â”¤ {{32}} â”œâ”€â”€â”€â”¤ {{22}} â”‚ {{23}} â”‚
    â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤ {{26}} â”œâ”€â”€â”€â”¤ {{28}} â”‚ {{29}} â”‚         â”‚ {{30}} â”‚ {{31}} â”œâ”€â”€â”€â”¤ {{33}} â”œâ”€â”€â”€â”¼â”€â”€â”€â”¤
    â”‚ {{24}} â”‚ {{25}} â”œâ”€â”€â”€â”˜   â””â”€â”€â”€â”´â”€â”€â”€â”˜         â””â”€â”€â”€â”´â”€â”€â”€â”˜   â””â”€â”€â”€â”¤ {{34}} â”‚ {{35}} â”‚
    â””â”€â”€â”€â”´â”€â”€â”€â”˜       â”Œâ”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â” â”Œâ”€â”€â”€â”¬â”€â”€â”€â”¬â”€â”€â”€â”       â””â”€â”€â”€â”´â”€â”€â”€â”˜
                    â”‚ {{36}} â”‚ {{37}} â”‚ {{38}} â”‚ â”‚ {{39}} â”‚ {{40}} â”‚ {{41}} â”‚
                    â””â”€â”€â”€â”´â”€â”€â”€â”´â”€â”€â”€â”˜ â””â”€â”€â”€â”´â”€â”€â”€â”´â”€â”€â”€â”˜


  plot_template_short: |2
    {{0}}{{1}}{{2}}{{3}}{{4}}{{5}} {{6}}{{7}}{{8}}{{9}}{{10}}{{11}}
    â‡˜{{12}}{{13}}{{14}}{{15}}{{16}} {{17}}{{18}}{{19}}{{20}}{{21}}â‡˜
     {{22}}{{23}}{{24}}{{25}}{{26}} {{27}}{{28}}{{29}}{{30}}{{31}}

base_layout:
  keys:
    # Row 1
    - - ["\t"]
      - [";" , "ğŸ˜œ"  , "#"]
      - ["," , "ğŸ˜œ"  , "?"]
      - ["." , "ğŸ˜œ"  , ":"]
      - ["u" , "U" , "*"]
      - ["y" , "Y" , "@"]
      - ["v" , "V" , "$"]
      - ["f" , "F" , "/"]
      - ["c" , "C" , "&"]
      - ["h" , "H" , "|"]
      - ["l" , "L" , "^"]
      - ["z" , "Z" , "1" ]
    # Row 2 (home row)
    - - ["ğŸ˜œ"]
      - ["a", "A", "~"]
      - ["o", "O", "["]
      - ["e", "E", "{"]
      - ["i", "I", "("]
      - ["p", "P", "<"]
      - ["d", "D", ">"]
      - ["r", "R", ")"]
      - ["t", "T", "}"]
      - ["s", "S", "]"]
      - ["n", "N", "!"]
      - ["+", "ğŸ˜œ" , "-"]
    # Row 3
    - - ["ğŸ˜œ"]
      - ["x", "X", "2"]
      - ["k", "K", "3"]
      - ["j", "J", "4"]
      - ["b", "B", "%"]
      - ["q", "Q", "5"]
      - ["m", "M", "6"]
      - ["w", "W", "\\"]
      - ["g", "G", "7"]
      - ["\"", "`", "'"]
      - ["=", "ğŸ˜œ", "8"]
      - ["ğŸ˜œ"]
    # Row 4, containing the spacebar
    - - ["9"]
      - ["0"]
      - [" ", "â†»", "_"] # esc
      - ["\n"]
      - ["âŒ«"]
      - ["âŒ¦"]

  fixed_keys:
    - [ false, false, false, false, false, false,                  false, false, false, false, false, false]
    - [ false, false, false, false, false, false,                  false, false, false, false, false, false]
    - [ false, false, false, false, false, false,                  false, false, false, false, false, false]
    - [                             false, false, false,   false, false, false                             ]

  # for NeoLayoutGenerator:
  # layers that shall not be permutated (starting from 0)
  fixed_layers: []

  # for GroupedLayoutGenerator:
  # number of consecutive symbols from base layout to group together generating a layout
  grouped_layers: 1

  # modifier types can be "hold", "one_shot", and "long_press"
  #
  # "hold" and "one_shot" modifiers require a field "value" holding a list of
  # either matrix positions or symbols acting as modifiers
  modifiers:
    - Left:
        type: hold
        value: [[5,2]]
      Right:
        type: hold
        value: [[14,2]]
    - Left:
        type: hold
        value: [[4,2]]
      Right:
        type: hold
        value: [[15,2]]
